language: python
python:
addons:
  chrome: stable
# current default Python on Travis CI
  - "3.7" 
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before-script:
  - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER/chromedriver_linux64.zip
  - mkdir $HOME/chromedriver && unzip /tmp/chromedriver.zip -d $HOME/chromedriver
  - export PATH=$HOME/chromedriver:$PATH
script:
  - python3 python3-selenium-headless.py
  - pytest
  - behave
